spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8&useSSL=false
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
#    nacos配置地址
    nacos:
      discovery:
        server-addr: localhost:8848
        #知道命名空间
#        namespace: 9d409d3e-94f3-4726-8da8-c04c1871187d
        # 知道集群名称
#        cluster-name: XY
        # 元数据
        metadata:
          instance: c
          version: v1
  #        服务名称
  application:
    name: user-centos

server:
  port: 8080
# 配置nacos